### PR TITLE
Added Jaccard and Log-Los

### PR DESCRIPTION
**Pull request by muschellij2**
I added Jaccard Index (https://en.wikipedia.org/wiki/Jaccard_index), which can be calculated from F1, but I figured it'd be good to have.  

Also - added log-loss, but it's a little odd given that the values are thresholded.

### CODE REVIEW

**Comment by Thie1e** [comment]
Hi, thanks a lot! I don't have a lot of time to check the additions now, but I'll get back to you. Best, Christian.

**Comment by Thie1e** [comment]
Hi, I've now checked the additions. 

I think adding the Jaccard-Index is a good idea, so I'm going to merge that and write a test. I'm also going to make the function lower case, because the other metric functions are in lower case, too.

Regarding the log-loss, did the supplied function work for you? `cutpointr` should have thrown an error, because it has to return a matrix with multiple rows for vector inputs, for example `log_loss(1:2, 4:5, 3:4, 7:8)` should return something like 

```
     log_loss
[1,] 379.9265
[2,] 449.0041
```

I changed `res = cbind(-1 * sum(res))` to `res = cbind(-1 * res)` in the function to make it work.

Anyway, I'm still trying to wrap my head around the meaning of that metric for a binary predictor, such as in this case. 

For a small `eps` the formula can be simplified to -1 * (fp + fn) * [some negative number]. The plot of cutpoint values vs. metric values (via `plot_metric`) has the same shape as the one from `misclassification_cost` for equal costs, where the latter is easier to interpret. `misclassification_cost` of course also finds the same optimal cutpoints at the minimal sum of misclassifications.

Was there a certain application for the log loss?

**Comment by muschellij2** [comment]
These seem like great enhancements! Many kaggle competitions use log loss
for the metric: https://www.kaggle.com/dansbecker/what-is-log-loss
Dice/Jaccard is what I use for most imaging applications.

Best,
John

**Comment by Thie1e** [comment]
Sure, on Kaggle we often develop a model for predicting probabilities and these are then judged by log-loss. `cutpointr` just dichotomizes the probabilities, as you've noted, and then we could just as well use `misclassification_cost` which is by default equal to the number of misclassifications, because it can be interpreted more easily than the log-loss and the "loss function" has the same shape. 

Did you actually use this in a Kaggle competition or somewhere else? Did it lead to an improvement? I'm just not aware of log-loss for purely binary predictions. Usually, we'd optimize the underlying model directly for log-loss.

**Comment by muschellij2** [comment]
I haven't used in Kaggle directly.  I've been using for other smaller
projects, but I think the addition of Jaccard/Dice and the proposed
addition of the misclassification loss you've described is sufficient
Best,
John

**Pull request merged**
